# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creation_de_profs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Creation_de_profs
from Creation_de_profs import*

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        self.subject_label = QtWidgets.QLabel(self.tab)
        self.subject_label.setObjectName("subject_label")
        self.horizontalLayout_2.addWidget(self.subject_label)


        self.subject_comboBox = QtWidgets.QComboBox(self.tab)
        self.subject_comboBox.setObjectName("subject_comboBox")
        self.horizontalLayout_2.addWidget(self.subject_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)


        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem("Nom"))
        self.tableWidget.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem("Heures totales"))
        self.tableWidget.setHorizontalHeaderItem(2, QtWidgets.QTableWidgetItem("Heures sup"))
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)


        self.addline_pushButton = QtWidgets.QPushButton(self.tab)
        self.addline_pushButton.setObjectName("addline_pushButton")
        self.addline_pushButton.clicked.connect(self.addlinetotable)
        self.verticalLayout.addWidget(self.addline_pushButton)


        self.save_pushButton = QtWidgets.QPushButton(self.tab)
        self.save_pushButton.setObjectName("save_pushButton")
        self.save_pushButton.clicked.connect(self.save)
        self.verticalLayout.addWidget(self.save_pushButton)


        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.subjects = Creation_de_profs.init()
        for element in self.subjects:
            self.subject_comboBox.addItem(element.label)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subject_label.setText(_translate("MainWindow", "Matière"))
        self.addline_pushButton.setText(_translate("MainWindow", "Ajouter ligne"))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Creation de profs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

    def addlinetotable(self):
        self.tableWidget.setRowCount(self.tableWidget.rowCount() + 1)

    def save(self):
        self.subjects[0].profs = []
        for i in range(self.tableWidget.rowCount()):
            nom = self.tableWidget.item(i, 0)
            heures = self.tableWidget.item(i, 1)
            sup = self.tableWidget.item(i, 2)
            if nom and heures and nom.text() != "" and heures.text != "" and sup and sup.text() != "":
                p = Creation_de_profs.Prof(nom.text(), int(heures.text()), int(sup.text()))
                self.subjects[0].profs.append(p)
                Creation_de_profs.save(self.subjects[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
