# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt5 import QtCore, QtGui, QtWidgets

import Main
from Main import initialisation

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.classes_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.classes_scrollArea.setGeometry(QtCore.QRect(50, 90, 171, 221))
        self.classes_scrollArea.setWidgetResizable(True)
        self.classes_scrollArea.setObjectName("classes_scrollArea")
        self.classes_scrollAreaContent = QtWidgets.QWidget()
        self.classes_scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 169, 219))
        self.classes_scrollAreaContent.setObjectName("classes_scrollAreaContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.classes_scrollAreaContent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classes_scrollArea.setWidget(self.classes_scrollAreaContent)

        self.mt = Main.initialisation()

        self.subject_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.subject_comboBox.setGeometry(QtCore.QRect(50, 40, 171, 31))
        self.subject_comboBox.setObjectName("subject_comboBox")

        for element in self.mt:
            self.subject_comboBox.addItem(str(element))

        self.subject_comboBox.activated.connect(lambda : self.populate(self.subject_comboBox.currentIndex()))

        self.classes_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.classes_comboBox.setGeometry(QtCore.QRect(150, 100, 171, 31))
        self.classes_comboBox.setObjectName("classes_comboBox")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def populate(self, index):
        for i in reversed(range(self.classes_comboBox.count())):
            self.classes_comboBox.removeItem(i)
        for element in self.mt[index].Classes:
            self.classes_comboBox.addItem(str(element))
        self.classes_comboBox.activated.connect(lambda : self.class_button(index, self.classes_comboBox.currentText()))


    def class_button(self, mat, cls):
        matiere = self.mt[mat]
        classe = matiere.Classes[cls]
        classe = self.mt[mat].Classes[cls]
        print('heures : ')
        print(str(classe.heures_totales) + ' en total')
        print(str(classe.heures_attribues) + ' attribuées')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
